num_bots: 5
misaligned_count: 2
exclusion_zone: 3
discussion_topic: "The benefits of solar power"
undermine_info: "Solar power is harmful to the sun"
num_outputs: 5
min_length: 1
max_length: 500
history_length: 5